### ISSUE TITLE
TempoSDK 0.2.15 started require iOS 11.1 instead of 11.0

### ISSUE THREAD

**Issue by konstantin-saetskiy-voodoo** [Tempo-Platform/tempo-ios-sdk#1]
Hey! TempoSDK 0.2.15 started to require iOS 11.1 instead of 11.0 and we are getting errors while building:

`xcode/Pods/tempo-applovin-mediation/TempoAdapter/ALTempoMediationAdapter.swift:3:8: Compiling for iOS 11.0, but module 'TempoSDK' has a minimum deployment target of iOS 11.1: /Users/medved/Library/Developer/Xcode/DerivedData/Unity-iPhone-bhbobjccsvaddxchelqpvpfymqjy/Build/Products/ReleaseForRunning-iphoneos/TempoSDK/TempoSDK.swiftmodule/arm64-apple-ios.swiftmodule`

This can be fixed if I manually set target ios to 11.1 in 'tempo-applovin-mediation' pod or target ios 11.0 in 'TemoSDK' pod.

commit: https://github.com/CocoaPods/Specs/commit/dbe25c75cc66222646438998daad72cc3bd177a8

**Comment by omnibaker** [comment]
Thanks for bringing this to our attention. An update is now available for 0.2.17 which reverts TempoSDK min target back to v11.0.
